version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: fituser
      POSTGRES_PASSWORD: fitpass
      POSTGRES_DB: fittrack
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=fittrack;Username=fituser;Password=fitpass
    ports:
      - "5000:80"

volumes:
  pgdata:
